### ISSUE TITLE
Institution View

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#17]
Hello! I came upon a small issue when searching for an item. When viewing the [E.H. Butler Library, Buffalo State Institution page](https://www.digitaltransgenderarchive.net/inst/zk51vg905), the list of "Digital Collections" does not include Discovery Resources. However, there is [one item](https://www.digitaltransgenderarchive.net/files/x633f1286) in the Discovery Resources collection from this institution. I want to make sure it is also listed on the institution page so that people can find it when viewing the Buffalo State page! This item appears in the "View All Items" search list.

As far as I can tell, this is the only instance of this happening and hopefully it is just a one time glitch!

**Comment by scande3** [comment]
Currently that list is generated by what is set on the Collection page. If you go to that collection on the Collection listing and select the "Edit" action, you should be able to see all the Institutions it has been associated with.

It may be possible to change this to auto-detect and update that in the future as items are added rather than it being set on the collection page.

I have updated that collection to link to that institution you mentioned. Thanks!

**Comment by ntantum** [comment]
Thank you! I will make sure to check the collection pages if I notice this issue again!
