### ISSUE TITLE
Featured Image for Collections

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#7]
Is there a way to change the featured image for a collection? (The image that appears on the collection listing page.)

We are hoping to switch some around and I can't seem to find this option. Let me know if I am just missing it!

**Comment by scande3** [comment]
The ETA for this has been moved to Tuesday evening.

**Comment by scande3** [comment]
This has now been added (apologies for the delay). To set a collection image, have a role of "admin" or "superuser" and be in an item in that collection. That item now has an action link to set it as the collection image. Let me know if this should be available to all administrative users rather than the higher authentication level I've set it to at the moment. Thanks!

**Comment by ntantum** [comment]
I think this higher authentication level is good. I tested it out and it works perfectly! Thanks, Steven!
